#!/usr/bin/env bash
apt update && apt upgrade -y
apt install python3 -y
pip install discord pillow flask
apt install git
git clone https://github.com/TiranoZero/Aula-Termux-Discord.py.git
apt install wget
apt install figlet

mv Aula-Termux-Discord.py base
mv base/removivel.vimrc ~/.vimrc
mkdir -p  ~/.vim/colors

mv base/monokai.vim ~/.vim/colors

adduser lord

rm  -r base
vim .bashrc

data=$(dialog --inputbox 'Digite o novo hostname' 10 31 --stdout)


echo "\n127.0.0.1 $data" >> /etc/hosts
echo "$data" > /etc/hostname
echo "$data" > /proc/sys/kernel/hostname

$(dialog --msgbox "Instalação completa, sua maquina vai reiniciar")
